// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBda9VMiMRG4PcNvFw0YQ5TZmBEoIEZF8E',
    appId: '1:687278476664:web:eec92912fe26347483cc8d',
    messagingSenderId: '687278476664',
    projectId: 'learnstream-deabb',
    authDomain: 'learnstream-deabb.firebaseapp.com',
    storageBucket: 'learnstream-deabb.appspot.com',
    measurementId: 'G-JJ743CR479',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7QzV5K3uCKgwN6a-XFCNqi6BRO9h6vU',
    appId: '1:687278476664:android:929777e72cceae1c83cc8d',
    messagingSenderId: '687278476664',
    projectId: 'learnstream-deabb',
    storageBucket: 'learnstream-deabb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKlSM66NSLd0zBGHQQ4sT2RTx3N0mU9XY',
    appId: '1:687278476664:ios:e3e1936a8c1c821583cc8d',
    messagingSenderId: '687278476664',
    projectId: 'learnstream-deabb',
    storageBucket: 'learnstream-deabb.appspot.com',
    iosClientId: '687278476664-8ki8anddiiajvr9g1mtvrfu746b90ma9.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnStream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKlSM66NSLd0zBGHQQ4sT2RTx3N0mU9XY',
    appId: '1:687278476664:ios:e3e1936a8c1c821583cc8d',
    messagingSenderId: '687278476664',
    projectId: 'learnstream-deabb',
    storageBucket: 'learnstream-deabb.appspot.com',
    iosClientId: '687278476664-8ki8anddiiajvr9g1mtvrfu746b90ma9.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnStream',
  );
}
